### ISSUE TITLE
USER STORY: Feedback as a User

### ISSUE THREAD

**Issue by Stephenkofipoku** [Stephenkofipoku/My-First-Agile-Project#5]
In order to provide anonymous feedback as **user**, I can **choose to hide my identity** in the **poll response**

# Acceptance Criteria

- The option should be provided as checkbox
- The checkbox should be "checked" by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include user name.

# Tasks
- [x] Update the view: the poll design (HTLM and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
