### ISSUE TITLE
USER STORY: Create a poll, manage a poll and publish a poll

### ISSUE THREAD

**Issue by Stephenkofipoku** [Stephenkofipoku/My-First-Agile-Project#6]
In order to automatically hide a poll as **administrator**, I can pick the **expiry date** while **publishing the poll**

# Acceptance Criteria

- The poll should appear at 11:59 PM at the target date
- The real estate of the "Poll" should be reserved on the home page. A message that says, "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
- The administrator expiry date should be at least 3 days after the current date.

# Tasks:
- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay Tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them.
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test functionality
